services:
  postgres:
    image: postgres:16
    container_name: jobtrack-postgres
    environment:
      POSTGRES_DB: jobtrack
      POSTGRES_USER: jobtrack_user
      POSTGRES_PASSWORD: jobtrack_pass
    ports:
      - "5432:5432"
    volumes:
      - jobtrack-data:/var/lib/postgresql/data

volumes:
  jobtrack-data: