services:
  postgres:
    image: postgres:16
    container_name: jobtrack-postgres
    environment:
      POSTGRES_DB: jobtrack
      POSTGRES_USER: jobtrack_user
      POSTGRES_PASSWORD: jobtrack_pass
    ports:
      - "5432:5432"
    volumes:
      - jobtrack-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: jobtrack-app
    depends_on:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/jobtrack
      DB_USERNAME: jobtrack_user
      DB_PASSWORD: jobtrack_pass
      JWT_SECRET: bjveuvBVUJBJVNBikvnbEUVJBbujfbeuikzbveujejvubevhebsvbehvbevbehb123456789
      JWT_EXPIRATION: 86400000
    ports:
      - "8080:8080"

volumes:
  jobtrack-data: