spring.application.name=jobtrack

spring.datasource.url=jdbc:postgresql://localhost:5432/jobtrack
spring.datasource.username=jobtrack_user
spring.datasource.password=jobtrack_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=bjveuvBVUJBJVNBikvnbEUVJBbujfbeuikzbveujejvubevhebsvbehvbevbehb123456789
jwt.expiration=86400000